version: 2.1
executors:
  builder:
    docker:
      - image: cimg/openjdk:8.0

jobs:
  build:
    executor: builder

    environment:
      JVM_OPTS: -Xmx16g
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "46:16:1f:87:64:31:75:9b:d5:26:8a:e5:c8:6e:45:ba"

      - checkout

      - run: git submodule sync

      - run: git submodule update --init

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew --stacktrace dist website

      - persist_to_workspace:
          root: build
          paths:
            - distributions

      - run:
          command: .circleci/publish.sh

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ./artifacts/distributions/


workflows:
  version: 2
  check:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
  deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/

